---
# tasks file for frontend
- name: copying frontend to instance
  copy:
    src: /home/ansible/3-Tier-application-proj/App/frontend/
    dest: /home/ec2-user/project/frontend/

- name: overwriting the app.js with jinja
  template:
    src: templates/app.js.j2
    dest: /home/ec2-user/project/frontend/app.js
      
- name: copying the docker compose file for frontend container
  copy:
    src: files/docker-compose.yml
    dest: /home/ec2-user/project/docker-compose.yml

- name: running the compose file with building images
  community.docker.docker_compose_v2:
    project_src: /home/ec2-user/project/
    build: "always"


